create table shipments (
  shipment_id text not null primary key,
  carrier text,
  bill_to_account_number text,
  invoice_date text,
  invoice_number text,
  payor text,
  tracking_number text,
  transportation_charge_amount text,
  net_charge_amount numeric,
  service_type text,
  ground_service text,
  shipment_date text,
  pod_delivery_date text,
  pod_delivery_time text,
  actual_weight_amount numeric,
  actual_weight_units text,
  rated_weight_amount numeric,
  rated_weight_units text,
  number_of_pieces text,
  bundle_number text,
  meter_number text,
  service_packaging text,
  dim_length numeric,
  dim_width numeric,
  dim_height numeric,
  dim_divisor numeric,
  dim_unit text,
  recipient_name text,
  recipient_company text,
  recipient_address_line_1 text,
  recipient_address_line_2 text,
  recipient_city text,
  recipient_state text,
  recipient_zip_code text,
  recipient_country_territory text,
  shipper_company text,
  shipper_name text,
  shipper_address_line_1 text,
  shipper_address_line_2 text,
  shipper_city text,
  shipper_state text,
  shipper_zip_code text,
  shipper_country_territory text,
  original_customer_reference text,
  original_ref_2 text,
  original_ref_3_po_number text,
  zone_code text
);

create table charges (
  charge_index integer not null,
  shipment_id text references shipments (shipment_id) on delete cascade ,
  amount numeric,
  description text,
  unique (charge_index, shipment_id)
);